DS-216: Custom Error Message
funidata/fudis pull request #233
Opened 2023-12-08 09:49 UTC by videoeero

2023-12-15 12:22 UTC, RiinaKuu requested changes

2023-12-15 12:22 UTC, RiinaKuu commented on ngx-fudis/projects/ngx-fudis/src/lib/components/form/radio-button-group/radio-button-group.stories.ts
> +					[type]="'required'"
Onko tämä turha? En löytänyt fudis-error-messagelle annettavaa inputtia nimellä type 🤷

2023-12-15 12:22 UTC, RiinaKuu commented on ngx-fudis/projects/ngx-fudis/src/lib/components/form/date/datepicker/datepicker.component.html
> +		<ng-content />
Onko tää tarkoituksella ilman `select="fudis-error-message"`?

2023-12-15 12:22 UTC, RiinaKuu commented on ngx-fudis/projects/ngx-fudis/src/lib/components/form/guidance/guidance.component.html
> +					<ng-content />
Tääkin on varmaan tarkoituksella ilman `select="fudis-error-message"`?

2023-12-15 12:22 UTC, RiinaKuu commented on ngx-fudis/projects/ngx-fudis/src/lib/components/form/guidance/guidance.component.ts
> +	@ContentChild(ContentDirective) content: ContentDirective;
Tätäkin varmaan johonkin tarvitaan, mitä en nyt vaan snaijaa 😬

2023-12-15 12:22 UTC, RiinaKuu commented on ngx-fudis/projects/dev/src/app/components/formExamples.component.ts
> +		// textInput: new FormControl<string | null | number>(null, [
Tätä sandboxia vois siistiä jos nää on tarkoitus poistaa. Samalla vois myös muokata templassa olevan tooltipin tekstin, koska se on nyt harhaanjohtava, koska sillä ei enää oo näitä validaattoreita.

2023-12-18 07:24 UTC, MayaMarjut commented on ngx-fudis/projects/ngx-fudis/src/lib/components/form/date/datepicker/datepicker.component.html
> +		<ng-content />
Tää on tarkoituksella

2023-12-18 07:24 UTC, MayaMarjut commented on ngx-fudis/projects/ngx-fudis/src/lib/components/form/guidance/guidance.component.html
> +					<ng-content />
Tää on myös tarkoituksella

2023-12-18 07:28 UTC, MayaMarjut commented on ngx-fudis/projects/ngx-fudis/src/lib/components/form/error-message/error-message/error-message.stories.ts
> +				*ngIf="mainFormGroup.controls['required'].touched"
Joo keskusteltiin tästä Eeron kaa ja tultiin siihen tulokseen et se on kehittäjän vastuulla käyttää näitä oikein, eli tarvitsee ton validaattorin invalid tilaan et se virhe ikoni näkyy. Tästä oon kirjoittanut myös Usage Guidelines osioon. Mutta siis hyvä olla tietoinen, koska Into kehittäjät voi kysellä tästä.

2023-12-18 08:15 UTC, MayaMarjut commented on ngx-fudis/projects/ngx-fudis/src/lib/utilities/form/readme.mdx
> +Max length validator does not prompt any error message but disable user to input more than allowed length of characters to the input field.
Oon sisällyttänyt ton dokumentaation sinne komponentin omaan dokumentaatioon. Tosta optioneiden määrästä ei kyllä musta ollu dokumentaatiota tuolla dropdownissa. ` Multiselect dropdown can have min and max length validators. Include `FudisValidators.minLength()` and/or `FudisValidators.maxLength()` in the form control validators with a threshold number and proper message property.` Oon poistanut tämän tekstin dropdownista. Nyt itseasiassa mietin, että kerran se toimii vain tuolla `multipleOption` valinnalla niin se pitäisi kyllä tarkentaa tuonne.

2023-12-18 08:17 UTC, MayaMarjut commented on ngx-fudis/projects/ngx-fudis/src/lib/utilities/form/readme.mdx
> +Max length validator does not prompt any error message but disable user to input more than allowed length of characters to the input field.
Mutta joo kerro mitä mieltä oot tästä rakenteesta. Ajattelin, että tää muuttuu tosi sekavaksi jos tässä alkaa kertomaan komponentti kohtaisi poikkeuksia. Esim just noiden min ja max validaation osalta.

2023-12-18 08:28 UTC, MayaMarjut commented on ngx-fudis/projects/ngx-fudis/src/lib/directives/form/input-base/input-base.directive.ts
> +	@ContentChild(ContentDirective) content: ContentDirective;
Joo on turha😄

2023-12-19 07:52 UTC, RiinaKuu approved these changes

2023-12-20 14:38 UTC, merged