[BREAKING CHANGE][Grid]: Remove marginTop and marginBottom input properties from Grid, replace usages with fudis spacing classes
funidata/fudis pull request #440
Opened 2024-09-18 16:09 UTC by xanxan

https://funidata.atlassian.net/browse/DS-368

BREAKING CHANGE:
- Remove marginTop and marginBottom input properties
- Remove references from tests, documentation and stories
- Replace usages with fudis spacing classes
- Refactor Grid directive to inherit classes given through the class property, so the spacing classes can be applied

Tarvitseeko scopettaa tiukemmin mitä kamaa classin kautta voidaan gridille syöttää? Esim. pelkästään fudiksen spacing-luokkia? Ja Halutaanko niiden käytöstä mainita erikseen mitään gridin dokumentaatiossa?

2024-09-20 10:17 UTC, RiinaKuu requested changes

2024-09-20 10:17 UTC, RiinaKuu commented on ngx-fudis/projects/ngx-fudis/src/lib/components/dialog/dialog.stories.ts
> +          <fudis-grid [columns]="{ xs: 1, sm: 2, md: 3 }" [classes]="['fudis-mt-sm fudis-mb-sm']">
Change above `<hr />` element to `<fudis-hr />`.
Grid columns' xs is always one so let's remove `xs: 1 `part from the JSON object.

2024-09-20 10:17 UTC, RiinaKuu commented on ngx-fudis/projects/ngx-fudis/src/lib/components/dialog/dialog.stories.ts
> +          <fudis-grid [classes]="['fudis-mt-md fudis-mb-md']">
Seems like this margin-top does not affect at all, `mat-dialog__content` class is overriding it.

2024-09-20 10:17 UTC, RiinaKuu commented on ngx-fudis/projects/ngx-fudis/src/lib/components/description-list/description-list.stories.ts
> +          <fudis-dl [variant]="'compact'" [classes]="['fudis-mt-none fudis-mb-none']">
In general I think this is a bad pattern.
Browser adds default styles (margins) to native `<dl>` element which we used to override with Grid's margin-top and margin-bottom values. I think we still want to override those values coming from the browser, so some king of logic for that should be added where `[classes]` input's values will then override the initial none values.

2024-09-28 13:24 UTC, videoeero approved these changes

2024-09-30 06:39 UTC, RiinaKuu approved these changes

2024-09-30 06:39 UTC, merged